package com.arkanoid.utils;

import java.io.*;
import java.nio.file.*;
import java.util.ArrayList;
import java.util.List;

public class StoreSaveSystem {
    private static final String SAVE_FILE = "store_data.txt";


    private static Path getSaveFilePath() {
        try {

            String resourcePath = StoreSaveSystem.class.getResource("/com/arkanoid/data").getPath();


            if (resourcePath.startsWith("/") && resourcePath.contains(":")) {
                resourcePath = resourcePath.substring(1);
            }

            Path savePath = Paths.get(resourcePath, SAVE_FILE);


            Files.createDirectories(savePath.getParent());

            return savePath;
        } catch (Exception e) {
            System.err.println("Error getting save path: " + e.getMessage());

            return Paths.get(SAVE_FILE);
        }
    }


    public static void saveStoreData(int selectedPaddle, int selectedBall,
                                     boolean[] unlockedPaddles, boolean[] unlockedBalls) {
        try {
            Path saveFile = getSaveFilePath();

            List<String> lines = new ArrayList<>();


            lines.add("# Arkanoid Store Save Data");
            lines.add("# Do not edit this file manually");
            lines.add("# Coins are managed separately by CoinStorage");
            lines.add("");


            lines.add("selected_paddle=" + selectedPaddle);
            lines.add("selected_ball=" + selectedBall);


            StringBuilder paddleStr = new StringBuilder("unlocked_paddles=");
            for (int i = 0; i < unlockedPaddles.length; i++) {
                paddleStr.append(unlockedPaddles[i] ? "1" : "0");
                if (i < unlockedPaddles.length - 1) {
                    paddleStr.append(",");
                }
            }
            lines.add(paddleStr.toString());


            StringBuilder ballStr = new StringBuilder("unlocked_balls=");
            for (int i = 0; i < unlockedBalls.length; i++) {
                ballStr.append(unlockedBalls[i] ? "1" : "0");
                if (i < unlockedBalls.length - 1) {
                    ballStr.append(",");
                }
            }
            lines.add(ballStr.toString());


            Files.write(saveFile, lines);

            System.out.println("✓ Store data saved to: " + saveFile);

        } catch (IOException e) {
            System.err.println("✗ Failed to save store data: " + e.getMessage());
            e.printStackTrace();
        }
    }


    public static StoreData loadStoreData() {
        Path saveFile = getSaveFilePath();

        if (!Files.exists(saveFile)) {
            System.out.println("No save file found at: " + saveFile + ", using default data");
            return getDefaultData();
        }

        try {
            List<String> lines = Files.readAllLines(saveFile);

            int selectedPaddle = 0;
            int selectedBall = 0;
            boolean[] unlockedPaddles = new boolean[]{true, false, false};
            boolean[] unlockedBalls = new boolean[]{true, false};


            for (String line : lines) {
                line = line.trim();


                if (line.isEmpty() || line.startsWith("#")) {
                    continue;
                }


                if (line.contains("=")) {
                    String[] parts = line.split("=", 2);
                    String key = parts[0].trim();
                    String value = parts[1].trim();

                    switch (key) {
                        case "selected_paddle":
                            selectedPaddle = Integer.parseInt(value);
                            break;

                        case "selected_ball":
                            selectedBall = Integer.parseInt(value);
                            break;

                        case "unlocked_paddles":
                            String[] paddleValues = value.split(",");
                            unlockedPaddles = new boolean[paddleValues.length];
                            for (int i = 0; i < paddleValues.length; i++) {
                                unlockedPaddles[i] = paddleValues[i].equals("1");
                            }
                            break;

                        case "unlocked_balls":
                            String[] ballValues = value.split(",");
                            unlockedBalls = new boolean[ballValues.length];
                            for (int i = 0; i < ballValues.length; i++) {
                                unlockedBalls[i] = ballValues[i].equals("1");
                            }
                            break;
                    }
                }
            }

            System.out.println("✓ Store data loaded from: " + saveFile);
            return new StoreData(selectedPaddle, selectedBall,
                    unlockedPaddles, unlockedBalls);

        } catch (IOException | NumberFormatException e) {
            System.err.println("✗ Failed to load store data: " + e.getMessage());
            e.printStackTrace();
            return getDefaultData();
        }
    }


    private static StoreData getDefaultData() {
        return new StoreData(
                0,                              // Default paddle selected
                0,                              // Default ball selected
                new boolean[]{true, false, false},  // Only first paddle unlocked
                new boolean[]{true, false}          // Only first ball unlocked
        );
    }


    public static void deleteSaveData() {
        Path saveFile = getSaveFilePath();
        try {
            Files.deleteIfExists(saveFile);
            System.out.println("✓ Store data deleted from: " + saveFile);
        } catch (IOException e) {
            System.err.println("✗ Failed to delete store data: " + e.getMessage());
        }
    }


    public static boolean hasSaveData() {
        return Files.exists(getSaveFilePath());
    }


    public static class StoreData {
        public final int selectedPaddle;
        public final int selectedBall;
        public final boolean[] unlockedPaddles;
        public final boolean[] unlockedBalls;

        public StoreData(int selectedPaddle, int selectedBall,
                         boolean[] unlockedPaddles, boolean[] unlockedBalls) {
            this.selectedPaddle = selectedPaddle;
            this.selectedBall = selectedBall;
            this.unlockedPaddles = unlockedPaddles;
            this.unlockedBalls = unlockedBalls;
        }

        @Override
        public String toString() {
            return String.format("StoreData{paddle=%d, ball=%d, " +
                            "paddlesUnlocked=%d, ballsUnlocked=%d}",
                    selectedPaddle, selectedBall,
                    countUnlocked(unlockedPaddles),
                    countUnlocked(unlockedBalls));
        }

        private int countUnlocked(boolean[] array) {
            int count = 0;
            for (boolean b : array) {
                if (b) count++;
            }
            return count;
        }
    }
}