package com.arkanoid.utils;

import java.io.*;
import java.nio.file.*;
import java.util.ArrayList;
import java.util.List;

public class StoreSaveSystem {
    private static final String SAVE_FILE = "store_data.txt";
    private static final String SAVE_DIR = "src/main/resources/com/arkanoid/data/";

    private static Path getSaveFilePath() {
        try {
            Path projectDir = Paths.get(System.getProperty("user.dir"));
            Path saveDir = projectDir.resolve(SAVE_DIR);
            Files.createDirectories(saveDir);
            return saveDir.resolve(SAVE_FILE);
        } catch (Exception e) {
            System.err.println("Error creating save directory: " + e.getMessage());
            try {
                Path fallbackDir = Paths.get(System.getProperty("user.dir"));
                return fallbackDir.resolve(SAVE_FILE);
            } catch (Exception ex) {
                return Paths.get(SAVE_FILE);
            }
        }
    }

    public static void saveStoreData(int selectedPaddle, int selectedBall,
                                     boolean[] unlockedPaddles, boolean[] unlockedBalls) throws IOException {
        Path saveFile = getSaveFilePath();

        List<String> lines = new ArrayList<>();

        lines.add("# Arkanoid Store Save Data");
        lines.add("# Do not edit this file manually");
        lines.add("# Coins are managed separately by CoinStorage");
        lines.add("");

        lines.add("selected_paddle=" + selectedPaddle);
        lines.add("selected_ball=" + selectedBall);

        StringBuilder paddleStr = new StringBuilder("unlocked_paddles=");
        for (int i = 0; i < unlockedPaddles.length; i++) {
            paddleStr.append(unlockedPaddles[i] ? "1" : "0");
            if (i < unlockedPaddles.length - 1) {
                paddleStr.append(",");
            }
        }
        lines.add(paddleStr.toString());

        StringBuilder ballStr = new StringBuilder("unlocked_balls=");
        for (int i = 0; i < unlockedBalls.length; i++) {
            ballStr.append(unlockedBalls[i] ? "1" : "0");
            if (i < unlockedBalls.length - 1) {
                ballStr.append(",");
            }
        }
        lines.add(ballStr.toString());

        Files.write(saveFile, lines, StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING);

        System.out.println("✓ Store data saved to: " + saveFile);
    }

    public static StoreData loadStoreData() {
        Path saveFile = getSaveFilePath();

        if (!Files.exists(saveFile)) {
            System.out.println("No save file found at: " + saveFile + ", using default data");
            return getDefaultData();
        }

        try {
            List<String> lines = Files.readAllLines(saveFile);

            int selectedPaddle = 0;
            int selectedBall = 0;
            boolean[] unlockedPaddles = new boolean[]{true, false, false};
            boolean[] unlockedBalls = new boolean[]{true, false};

            for (String line : lines) {
                line = line.trim();

                if (line.isEmpty() || line.startsWith("#")) {
                    continue;
                }

                if (line.contains("=")) {
                    String[] parts = line.split("=", 2);
                    if (parts.length < 2) continue;

                    String key = parts[0].trim();
                    String value = parts[1].trim();

                    switch (key) {
                        case "selected_paddle":
                            selectedPaddle = parseIntSafe(value, 0);
                            break;

                        case "selected_ball":
                            selectedBall = parseIntSafe(value, 0);
                            break;

                        case "unlocked_paddles":
                            unlockedPaddles = parseBooleanArray(value, new boolean[]{true, false, false});
                            break;

                        case "unlocked_balls":
                            unlockedBalls = parseBooleanArray(value, new boolean[]{true, false});
                            break;
                    }
                }
            }

            System.out.println("✓ Store data loaded from: " + saveFile);
            return new StoreData(selectedPaddle, selectedBall, unlockedPaddles, unlockedBalls);

        } catch (IOException e) {
            System.err.println("✗ Failed to load store data: " + e.getMessage());
            return getDefaultData();
        }
    }

    private static int parseIntSafe(String value, int defaultValue) {
        try {
            return Integer.parseInt(value);
        } catch (NumberFormatException e) {
            System.err.println("Invalid integer value: " + value + ", using default: " + defaultValue);
            return defaultValue;
        }
    }

    private static boolean[] parseBooleanArray(String value, boolean[] defaultValue) {
        try {
            String[] values = value.split(",");
            boolean[] result = new boolean[values.length];
            for (int i = 0; i < values.length; i++) {
                result[i] = values[i].trim().equals("1");
            }
            return result;
        } catch (Exception e) {
            System.err.println("Invalid boolean array: " + value + ", using default");
            return defaultValue;
        }
    }

    public static StoreData getDefaultData() {
        return new StoreData(
                0,
                0,
                new boolean[]{true, false, false},
                new boolean[]{true, false}
        );
    }

    public static void deleteSaveData() {
        Path saveFile = getSaveFilePath();
        try {
            Files.deleteIfExists(saveFile);
            System.out.println("✓ Store data deleted from: " + saveFile);
        } catch (IOException e) {
            System.err.println("✗ Failed to delete store data: " + e.getMessage());
        }
    }

    public static boolean hasSaveData() {
        return Files.exists(getSaveFilePath());
    }

    public static class StoreData {
        public final int selectedPaddle;
        public final int selectedBall;
        public final boolean[] unlockedPaddles;
        public final boolean[] unlockedBalls;

        public StoreData(int selectedPaddle, int selectedBall,
                         boolean[] unlockedPaddles, boolean[] unlockedBalls) {
            this.selectedPaddle = selectedPaddle;
            this.selectedBall = selectedBall;
            this.unlockedPaddles = unlockedPaddles;
            this.unlockedBalls = unlockedBalls;
        }

        @Override
        public String toString() {
            return String.format("StoreData{paddle=%d, ball=%d, paddlesUnlocked=%d, ballsUnlocked=%d}",
                    selectedPaddle, selectedBall,
                    countUnlocked(unlockedPaddles),
                    countUnlocked(unlockedBalls));
        }

        private int countUnlocked(boolean[] array) {
            int count = 0;
            for (boolean b : array) {
                if (b) count++;
            }
            return count;
        }
    }
}